/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bloodbankAdminRole;

import Business.Blood.BloodDirectory;
import Business.Blood.BloodGroup;
import Business.Blood.BloodSpecs;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * @author mihir
 */
public class BloodDonation extends javax.swing.JPanel {
 private ButtonGroup bg1= new ButtonGroup();
 private int opt;
  JPanel userProcessContainer;
  private BloodGroup bldgrp;
  private BloodSpecs bldsps;
  private BloodDirectory BldDir;
    /**
     * Creates new form BloodDonation
     */
    public BloodDonation(JPanel userProcessContainer, BloodDirectory blooddir,BloodGroup bg) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.bldgrp=bg ;
        bldsps=new BloodSpecs();
       this.BldDir=blooddir;
        groupbutton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _AjRadioButton1 = new javax.swing.JRadioButton();
        AjRadioButton2 = new javax.swing.JRadioButton();
        _BjRadioButton3 = new javax.swing.JRadioButton();
        BjRadioButton4 = new javax.swing.JRadioButton();
        _OjRadioButton5 = new javax.swing.JRadioButton();
        OjRadioButton6 = new javax.swing.JRadioButton();
        _ABjRadioButton7 = new javax.swing.JRadioButton();
        ABjRadioButton8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        volTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Blood Donation");

        jLabel2.setText("Donor Name:");

        jLabel3.setText("Select Blood Group:");

        _AjRadioButton1.setText("-A");
        _AjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _AjRadioButton1ActionPerformed(evt);
            }
        });

        AjRadioButton2.setText("+A");
        AjRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjRadioButton2ActionPerformed(evt);
            }
        });

        _BjRadioButton3.setText("-B");

        BjRadioButton4.setText("+B");

        _OjRadioButton5.setText("-O");

        OjRadioButton6.setText("+O");

        _ABjRadioButton7.setText("-AB");

        ABjRadioButton8.setText("+AB");

        jLabel4.setText("Volume:");

        nametxt.setColumns(15);

        volTxt.setColumns(7);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_OjRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OjRadioButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_ABjRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ABjRadioButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_AjRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AjRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_BjRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BjRadioButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(87, 87, 87)
                        .addComponent(submitBtn)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_AjRadioButton1)
                    .addComponent(AjRadioButton2)
                    .addComponent(_BjRadioButton3)
                    .addComponent(BjRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_OjRadioButton5)
                    .addComponent(OjRadioButton6)
                    .addComponent(_ABjRadioButton7)
                    .addComponent(ABjRadioButton8))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(jButton2))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjRadioButton2ActionPerformed

    private void _AjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__AjRadioButton1ActionPerformed
    opt=1;
    
// TODO add your handling code here:
    }//GEN-LAST:event__AjRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String Name=nametxt.getText();
        int vol=Integer.parseInt(volTxt.getText());
        bldsps.setDonorName(Name);
        bldsps.setVolume(vol);
        //..............adding blood to stocks..................
        if(AjRadioButton2.isSelected()){
           
            int a=bldgrp.getApositive();
            a=a+vol;
            bldgrp.setApositive(a);
            bldsps.setBloodGroup("A+ve");
           }
        if(_AjRadioButton1.isSelected()){
           
            int a=bldgrp.getAnegative();
            a=a+vol;
            bldgrp.setAnegative(a);
             bldsps.setBloodGroup("A-ve");
           }
         if(_BjRadioButton3.isSelected()){
           
            int a=bldgrp.getBnegative();
            a=a+vol;
            bldgrp.setBnegative(a);
             bldsps.setBloodGroup("B-ve");
           }
         if(BjRadioButton4.isSelected()){
           
            int a=bldgrp.getBpositive();
            a=a+vol;
            bldgrp.setBpositive(a);
             bldsps.setBloodGroup("B+ve");
           }
         if(_OjRadioButton5.isSelected()){
           
            int a=bldgrp.getOnegative();
            a=a+vol;
            bldgrp.setOnegative(a);
             bldsps.setBloodGroup("O-ve");
           }
           if(OjRadioButton6.isSelected()){
           
            int a=bldgrp.getOpositive();
            a=a+vol;
            bldgrp.setOpositive(a);
             bldsps.setBloodGroup("O-ve");
           }
          if(_ABjRadioButton7.isSelected()){
           
            int a=bldgrp.getAbnegative();
            a=a+vol;
            bldgrp.setAbnegative(a);
             bldsps.setBloodGroup("AB-ve");
           }
            if(ABjRadioButton8.isSelected()){
           
            int a=bldgrp.getABpositive();
            a=a+vol;
            bldgrp.setABpositive(a);
             bldsps.setBloodGroup("AB+ve");}
            
              BldDir.CreateBloodSpec( Name, bldsps.getBloodGroup(), vol);
              
           
        
        
    //    CreateBloodSpec(Name, BloodGroup,vol);
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed
public void groupbutton(){
   // ButtonGroup bg1= new ButtonGroup();
        ABjRadioButton8.setActionCommand("ABjRadioButton8");
    bg1.add(ABjRadioButton8);
   AjRadioButton2.setActionCommand("AjRadioButton2");
    bg1.add(AjRadioButton2);
    
    BjRadioButton4.setActionCommand("BjRadioButton4");
    bg1.add(BjRadioButton4);
    
    OjRadioButton6.setActionCommand("OjRadioButton6");
    bg1.add(OjRadioButton6);
    
    _ABjRadioButton7.setActionCommand("_ABjRadioButton7");
    bg1.add(_ABjRadioButton7);
    
    _AjRadioButton1.setActionCommand("_AjRadioButton1");
    bg1.add(_AjRadioButton1);
    
    _BjRadioButton3.setActionCommand("_BjRadioButton3");
    bg1.add(_BjRadioButton3);
    
    _OjRadioButton5.setActionCommand("_OjRadioButton5");
    bg1.add(_OjRadioButton5);
   // btnsel = String.valueOf(bg1.getSelection());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABjRadioButton8;
    private javax.swing.JRadioButton AjRadioButton2;
    private javax.swing.JRadioButton BjRadioButton4;
    private javax.swing.JRadioButton OjRadioButton6;
    private javax.swing.JRadioButton _ABjRadioButton7;
    private javax.swing.JRadioButton _AjRadioButton1;
    private javax.swing.JRadioButton _BjRadioButton3;
    private javax.swing.JRadioButton _OjRadioButton5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField volTxt;
    // End of variables declaration//GEN-END:variables
}
