/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bloodbankAdminRole;

import Business.Blood.BloodDirectory;
import Business.Blood.BloodGroup;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BloodBankStaffOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mihir
 */
public class BloodBankMain extends javax.swing.JPanel {
    private  JPanel userProcessContainer;
 
    private BloodDirectory blooddir;
    private BloodGroup bg;
    private BloodBankStaffOrganization BloodOrg;
    private UserAccount account;
    private Organization organization;
    private EcoSystem business;
    /**
     * Creates new form BloodBankMain
     */
    public BloodBankMain(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.BloodOrg=(BloodBankStaffOrganization)organization;
        this.account=account;
        this.organization=organization;
        this.business=business;
       this.blooddir=new BloodDirectory();
       this.bg=new BloodGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDonation = new javax.swing.JButton();
        reserves = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        donorRecords = new javax.swing.JButton();

        jLabel1.setText("Blood Bank");

        addDonation.setText("Add Blood Donation");
        addDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonationActionPerformed(evt);
            }
        });

        reserves.setText("Blood Bank Reserves");
        reserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservesActionPerformed(evt);
            }
        });

        jButton3.setText("Blood Bank Work Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        donorRecords.setText("Donor Records");
        donorRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reserves)
                            .addComponent(addDonation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(donorRecords)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(addDonation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reserves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donorRecords)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonationActionPerformed
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("BloodDonation", new BloodDonation(userProcessContainer,blooddir,bg));
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_addDonationActionPerformed

    private void reservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservesActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Stock", new Stock(userProcessContainer,bg));
        layout.next(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_reservesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("BloodbankadminWorkArea", new BloodbankadminWorkArea( userProcessContainer, account,organization,business));
        layout.next(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void donorRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRecordsActionPerformed
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DonorRecords", new DonorRecords(userProcessContainer,blooddir));
        layout.next(userProcessContainer);  
        // TODO add your handling code here:
    }//GEN-LAST:event_donorRecordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonation;
    private javax.swing.JButton donorRecords;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reserves;
    // End of variables declaration//GEN-END:variables
}
