/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bloodbankAdminRole;

import Business.Blood.BloodDirectory;
import Business.Blood.BloodGroup;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BloodBankStaffOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mihir
 */
public class BloodBankMain extends javax.swing.JPanel {
    private  JPanel userProcessContainer;
 
    
   // private BloodGroup bg;
    private BloodBankStaffOrganization BloodOrg;
    private UserAccount account;
 private Enterprise enterprise;
    private EcoSystem business;
    
    /**
     * Creates new form BloodBankMain
     */
    public BloodBankMain(JPanel userProcessContainer, UserAccount account, BloodBankStaffOrganization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.BloodOrg= organization;
        this.account=account;
        this.business=business;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDonation = new javax.swing.JButton();
        reserves = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        donorRecords = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Blood Bank");

        addDonation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDonation.setText("Add Blood Donation");
        addDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonationActionPerformed(evt);
            }
        });

        reserves.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserves.setText("Blood Bank Reserves");
        reserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservesActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Blood Bank Work Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        donorRecords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        donorRecords.setText("Donor Records");
        donorRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRecordsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mihir\\Desktop\\blood-icon-1.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDonation)
                            .addComponent(jButton3)
                            .addComponent(donorRecords)
                            .addComponent(reserves))
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(addDonation)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(donorRecords)
                        .addGap(37, 37, 37)
                        .addComponent(reserves))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonationActionPerformed
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("BloodDonation", new BloodDonation(userProcessContainer,BloodOrg));
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_addDonationActionPerformed

    private void reservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservesActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Stock", new Stock(userProcessContainer,BloodOrg));
        layout.next(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_reservesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("BloodbankadminWorkArea", new BloodbankadminWorkArea( userProcessContainer, account,BloodOrg,business,enterprise));
        layout.next(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void donorRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRecordsActionPerformed
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DonorRecords", new DonorRecords(userProcessContainer,BloodOrg));
        layout.next(userProcessContainer);  
        // TODO add your handling code here:
    }//GEN-LAST:event_donorRecordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonation;
    private javax.swing.JButton donorRecords;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reserves;
    // End of variables declaration//GEN-END:variables
}
