/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bloodbankAdminRole;

import Business.Blood.BloodGroup;
import Business.Blood.BloodSpecs;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mihir
 */
public class Stock extends javax.swing.JPanel {
     private JPanel userProcessContainer;
     private BloodGroup bg;
    /**
     * Creates new form BloodBankProcessWorkRequest
     */
    public Stock(  JPanel userProcessContainer, BloodGroup BloodGroup) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.bg=BloodGroup;
    populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A+", null},
                {"A-", null},
                {"B+", null},
                {"B-", null},
                {"O+", null},
                {"O-", null},
                {"AB+", null},
                {"AB-", null}
            },
            new String [] {
                "Blood Group", "Volume"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Blood Bank Stock");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void populateTable(){
     
     DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
   /*
     Object col[] = new Object[4];
            col[0] = String.valueOf(bg.getApositive());
            col[1] = String.valueOf(bg.getBpositive());
            col[2] =String.valueOf( bg.getABpositive());
            col[3] = String.valueOf(bg.getOpositive());
            tm.addColumn(col);      */
            
            

            tm.setValueAt( String.valueOf(bg.getApositive()), 0, 1);
            tm.setValueAt( String.valueOf(bg.getAnegative()), 1, 1);
            tm.setValueAt( String.valueOf(bg.getBpositive()), 2, 1);
            tm.setValueAt( String.valueOf(bg.getBnegative()), 3, 1);
            tm.setValueAt( String.valueOf(bg.getOpositive()), 4, 1);
            tm.setValueAt( String.valueOf(bg.getOnegative()), 5, 1);
            tm.setValueAt( String.valueOf(bg.getABpositive()), 6, 1);
            tm.setValueAt( String.valueOf(bg.getAbnegative()), 7, 1);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
