/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CFRAdminRole;

import Business.CrowdFunding.CFRFundingOrgsDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author nikhi
 */
public class CFRStratAddFundOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CFRStratAddFundOrgJPanel
     */
    
     JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    private CFRFundingOrgsDirectory fundorgDir;
    
    public CFRStratAddFundOrgJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.fundorgDir = new CFRFundingOrgsDirectory();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fundOrgtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        categorytxt = new javax.swing.JTextField();
        mbtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ADD FUNDING ORGS'");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 23, 150, 23));

        jLabel2.setText("ORGANIZATION NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 76, -1, -1));

        jLabel3.setText("CATEGORY");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 148, 80, -1));

        jLabel4.setText("EMAIL ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 76, -1, -1));

        jLabel5.setText("TELEPHONE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 148, -1, -1));
        add(fundOrgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 73, 100, -1));
        add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 73, 110, -1));
        add(categorytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 145, 100, -1));
        add(mbtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 136, 110, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jButton2.setText("BACK'");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String fund_org_name = fundOrgtxt.getText();
 String Category = categorytxt.getText();
  String email = emailtxt.getText();
  Long mb_num = Long.parseLong(mbtxt.getText());
        
fundorgDir.CreateFundingOrg(fund_org_name, Category, email, mb_num);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CFRStrategistWorkAreaJPanel cfrsjp = (CFRStrategistWorkAreaJPanel) component;
       // cfrsjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categorytxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fundOrgtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mbtxt;
    // End of variables declaration//GEN-END:variables
}
